# Generated by Django 5.2 on 2026-02-08 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the itinerary", max_length=200
                    ),
                ),
                ("start_date", models.DateField(help_text="Start date of the trip")),
                (
                    "days",
                    models.PositiveIntegerField(
                        help_text="Number of days for the trip"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to="destinations.destination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerary",
                "verbose_name_plural": "Itineraries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DayPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Day number in the itinerary"
                    ),
                ),
                ("plan", models.TextField(help_text="Detailed plan for the day")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_plans",
                        to="itineraries.itinerary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Day Plan",
                "verbose_name_plural": "Day Plans",
                "ordering": ["day_number"],
                "unique_together": {("itinerary", "day_number")},
            },
        ),
    ]
