# Generated by Django 5.2 on 2026-02-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the destination", max_length=200
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country where the destination is located",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the destination"),
                ),
                ("avg_budget", models.IntegerField(help_text="Average budget in INR")),
                (
                    "best_season",
                    models.CharField(
                        choices=[
                            ("Spring", "Spring (March-May)"),
                            ("Summer", "Summer (June-August)"),
                            ("Autumn", "Autumn (September-November)"),
                            ("Winter", "Winter (December-February)"),
                            ("Year-round", "Year-round"),
                        ],
                        help_text="Best season to visit (e.g., Summer, Winter, Monsoon)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
                "ordering": ["name"],
            },
        ),
    ]
